spring:
  application:
    name: supplier-service
  profiles:
    default: local
  data:
    mongodb:
      auto-index-creation: true

---
spring:
  config:
    activate:
      on-profile: "!test"
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8888}?fail-fast=true&max-attempts=6&initial-interval=1000&max-interval=5000&multiplier=1.5"
